### ISSUE TITLE
Can make logic more concise

### ISSUE THREAD

**Issue by sima-qian** [fac-15/CCSM_ToDo2#11]
![image](https://user-images.githubusercontent.com/29804933/48257335-25377f00-e40a-11e8-91bd-73838ce28438.png)

This can be nicely shortened to `if (!todo.done)`.

**Comment by sima-qian** [comment]
In fact, this whole block:

![image](https://user-images.githubusercontent.com/29804933/48257463-7e9fae00-e40a-11e8-92d4-3a2998330596.png)

could be:

```
todo.done = !todo.done;
return todo;
```

**Comment by boi87** [comment]
Thanks so much for pointing this out. It is always better to write more concisely.
Shortened as suggested! 
:blush:
