### ISSUE TITLE
markToDo func contains useless code

### ISSUE THREAD

**Issue by teenie-quaggard** [fac-15/CCSM_ToDo2#14]
![screen shot 2018-11-09 at 10 31 37](https://user-images.githubusercontent.com/37771591/48257615-e229db80-e40a-11e8-8978-d59089148145.png)

**Comment by HStewart23** [comment]
We know this code has a logical purpose, but you don't test for that purpose. It might be worth seeing if you can write a test to test you toggle from true to false and false to true.

**Comment by onwordi** [comment]
Thanks! There was a error in our merge. This has been resolved 👍
